language: node_js
node_js:
    - "node"
addons:
    apt:
        packages:
            - libusb-dev
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libusb-dev; fi
    - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/travis/libusb/1.0.20/lib/pkgconfig"
os:
    - linux
    - osx
notifications:
    email: false
